"""Test script to mock agent behavior and demonstrate MCP tool exposure issue.

This script demonstrates:
1. Current issue: Agent receives minimal prompt without tool information
2. Expected behavior: Agent should see available MCP tools and filesystem structure
"""

import asyncio
from unittest.mock import Mock, MagicMock

from src.agent import CodeActAgent
from codeact_mcp.config import Config
from codeact_mcp.mcp_registry import MCPRegistry, MCPToolInfo


def create_mock_mcp_registry() -> MCPRegistry:
    """Create a mock MCP registry with sample tools."""
    registry = Mock(spec=MCPRegistry)

    # Mock tools from different MCP servers
    tavily_tools = [
        MCPToolInfo(
            name="tavily_search",
            description="Search the web using Tavily search engine",
            input_schema={
                "type": "object",
                "properties": {
                    "query": {"type": "string", "description": "Search query"},
                    "max_results": {"type": "integer", "description": "Maximum results", "default": 10}
                },
                "required": ["query"]
            },
            server_name="tavily"
        )
    ]

    filesystem_tools = [
        MCPToolInfo(
            name="read_file",
            description="Read contents of a file",
            input_schema={
                "type": "object",
                "properties": {
                    "path": {"type": "string", "description": "File path to read"}
                },
                "required": ["path"]
            },
            server_name="filesystem"
        ),
        MCPToolInfo(
            name="write_file",
            description="Write content to a file",
            input_schema={
                "type": "object",
                "properties": {
                    "path": {"type": "string", "description": "File path to write"},
                    "content": {"type": "string", "description": "Content to write"}
                },
                "required": ["path", "content"]
            },
            server_name="filesystem"
        ),
        MCPToolInfo(
            name="list_directory",
            description="List contents of a directory",
            input_schema={
                "type": "object",
                "properties": {
                    "path": {"type": "string", "description": "Directory path to list"}
                },
                "required": ["path"]
            },
            server_name="filesystem"
        )
    ]

    github_tools = [
        MCPToolInfo(
            name="create_issue",
            description="Create a new GitHub issue",
            input_schema={
                "type": "object",
                "properties": {
                    "repo": {"type": "string", "description": "Repository name (owner/repo)"},
                    "title": {"type": "string", "description": "Issue title"},
                    "body": {"type": "string", "description": "Issue body"}
                },
                "required": ["repo", "title"]
            },
            server_name="github"
        )
    ]

    # Mock get_all_tools to return organized tools
    registry.get_all_tools.return_value = {
        "tavily": tavily_tools,
        "filesystem": filesystem_tools,
        "github": github_tools
    }

    return registry


def create_mock_config() -> Config:
    """Create a mock config."""
    config = Mock(spec=Config)

    # Mock LLM client
    mock_llm = MagicMock()
    config.get_llm_client.return_value = mock_llm

    # Mock LLM definition
    config.llm_definition = Mock()
    config.llm_definition.provider = "openai"
    config.llm_definition.model_id = "gpt-4"

    # Mock MCP config with tool_exposure_mode
    config.mcp = Mock()
    config.mcp.tool_exposure_mode = "summary"

    return config


def print_section(title: str, content: str):
    """Pretty print a section."""
    print("\n" + "="*80)
    print(f"  {title}")
    print("="*80)
    print(content)
    print("="*80 + "\n")


async def main():
    """Demonstrate the issue and expected behavior."""

    print("\n" + "🔍 MOCK AGENT BEHAVIOR TEST: MCP Tool Exposure Issue".center(80))
    print("="*80)

    # Create mocks
    config = create_mock_config()
    mcp_registry = create_mock_mcp_registry()

    # Create agent
    agent = CodeActAgent(config)

    # Get the tool summary that should be in the prompt
    tool_summary = agent._get_tool_summary(mcp_registry)

    print_section(
        "📊 TOOL SUMMARY (Generated by _get_tool_summary)",
        tool_summary
    )

    # Get the actual system message the agent uses
    current_system_message = agent._build_system_message(tool_summary)

    print_section(
        "❌ CURRENT SYSTEM MESSAGE (What agent actually sees)",
        current_system_message
    )

    # Show what the system message SHOULD contain (this is just for display)
    expected_system_message = """Write Python code to accomplish tasks using execute_code tool.

AVAILABLE MCP SERVERS AND TOOLS:
[The tool summary would be displayed here]

WORKSPACE STRUCTURE:
- tools/: Contains Python modules for each MCP server
  - tools/tavily.py: Import tavily tools (e.g., from tools.tavily import tavily_search)
  - tools/filesystem.py: Import filesystem tools (e.g., from tools.filesystem import read_file)
  - tools/github.py: Import github tools (e.g., from tools.github import create_issue)
- tools/docs/: Detailed documentation for each tool in Markdown format
  - tools/docs/tavily_search.md: Full documentation for tavily_search
  - tools/docs/read_file.md: Full documentation for read_file
  - (etc. for each tool)
- results/: Save your output files here
- data/: Input data files (if any)

HOW TO USE MCP TOOLS:
1. Tools are exposed as Python APIs in the sandbox environment
2. Import tools from the tools module: from tools.{server_name} import {tool_name}
3. To discover available tools, you can:
   - Read the AVAILABLE MCP SERVERS AND TOOLS section above for a quick overview
   - List files in tools/ directory to see available MCP server modules
   - Read tools/docs/*.md files for detailed documentation on specific tools

EXAMPLE WORKFLOW:
```python
# Import the tool you need
from tools.tavily import tavily_search
import json

# Use the tool
results = tavily_search(query="AI agents", max_results=5)

# Process data in the sandbox (don't pass large data to agent context!)
filtered = [r for r in results if r.get('score', 0) > 0.7]

# Save results
with open('results/search_results.json', 'w') as f:
    json.dump(filtered, f, indent=2)

print(f"Found {len(filtered)} high-quality results")
```

GUIDELINES:
- Use relative paths: Path("results/output.csv")
- NOT absolute paths: NOT /workspace/results/
- Use stdlib (pathlib, csv, json, etc.) for data processing
- Use try/except for error handling
- Print summary of results (not the full data!)

On errors: read the error message, fix code, retry."""

    print_section(
        "✅ EXPECTED SYSTEM MESSAGE (What agent should see)",
        expected_system_message
    )

    # Analysis
    print("\n" + "📋 ISSUE ANALYSIS".center(80))
    print("="*80)
    print("""
PROBLEM:
  The _build_system_message() method in agent.py receives a 'tool_summary'
  parameter but IGNORES it completely. This results in agents having NO
  knowledge of available MCP tools.

CURRENT BEHAVIOR:
  - Agent sees only basic workspace structure
  - No information about available MCP servers
  - No guidance on how to import tools
  - No explanation that tools are Python APIs

EXPECTED BEHAVIOR (from article):
  - Agents aware of MCP servers (name, description, location)
  - Clear filesystem structure showing where tools and docs are located
  - Progressive tool discovery: agents can read docs on-demand
  - Explicit instruction that tools should be imported as Python APIs

TOKEN EFFICIENCY PATTERN:
  - Summary mode: Brief listing of servers + filesystem navigation hints (~500 tokens)
  - Detailed mode: Full tool signatures in prompt (~2000 tokens)
  - Both modes support on-demand doc reading for full details
  - This achieves 98.7% token reduction vs. traditional ReAct patterns
    """)
    print("="*80 + "\n")

    print("✨ Test complete! The issue has been demonstrated.\n")


if __name__ == "__main__":
    asyncio.run(main())
